intent_to_functionality_dict = {
    "covid_stats": "covid_statistics_form",
    "EODY_faq": "no_action",
    "ask_chitchat": "no_action",
    "mask_faq": "no_action",
    "vaccines": "no_action",
    "time_declare": "no_action",
    "pharma_search": "pharmacy_form",
    "insult": "no_action",
    "affirmative": "no_action",
    "negative": "no_action",
    "greetings": "no_action",  # maybe tell we haven't greeted ourselves
    "stop_executing": "no_action",
    "region_declare": "no_action",
    "goodbye": "no_action",
    "thank_you": "no_action",
    "didnt_understand": "no_action",
    "am_i_ill": "ill_questionnaire_form",
    "why_avoid_pharma": "no_action",
    "what_to_do_if_positive": "what_to_do_if_positive",
    "symptoms": "symptoms",
    "whats_your_name": "no_action",
    "ways_of_protection": "ways_of_protection",
    "underlying_conditions": "underlying_conditions",
    "personal_ways_of_protection": "ways_of_protection",
    "collective_ways_of_protection": "ways_of_protection",
    "all_ways_of_protection": "ways_of_protection",
    "test_cost": "test_cost",
    "pcr_test_cost": "test_cost",
    "rapid_test_cost": "test_cost",
    "all_test_cost": "test_cost",
    "self_test": "no_action",
    "all_of_them": "no_action",
    "test_types": "test_types",
    "general_knowledge_tests": "no_action",
    "out_of_scope": "no_action",
    "vaccine_stats": "vaccine_stats_form",
    "find_new_icus": "icu_stats_form",
    "positive_feedback": "no_action",
    "affirmative+covid_stats": "covid_statistics_form",
    "affirmative+pharma_search": "pharmacy_form",
    "affirmative+find_new_icus": "icu_stats_form",
    "affirmative+vaccine_stats": "vaccine_stats_form",
    "negative+covid_stats": "covid_statistics_form",
    "negative+pharma_search": "pharmacy_form",
    "negative+find_new_icus": "icu_stats_form",
    "negative+vaccine_stats": "vaccine_stats_form",
    "negative+thank_you": "no_action",
    "greetings+covid_stats": "covid_statistics_form",
    "greetings+pharma_search": "pharmacy_form",
    "greetings+ask_chitchat": "no_action",
    "thank_you+covid_stats": "covid_statistics_form",
    "greetings+whats_your_name": "no_action",
    "what_is_ilsp+what_is_athena": "no_action",
    "why_theano": "no_action",
    "may_i_ask": "no_action",
    "sorry": "no_action",
    "what_is_athena": "no_action",
    "what_is_ilsp": "no_action",
    "no_action": "no_action",
}


limited_intent_to_functionality_dict = {
    "covid_stats": "covid_statistics_form",
    "EODY_faq": "no_action",
    "ask_chitchat": "no_action",
    "mask_faq": "no_action",
    "vaccines": "no_action",
    "pharma_search": "pharmacy_form",
    "greetings": "no_action",  # maybe tell we haven't greeted ourselves
    "goodbye": "no_action",
    "thank_you": "no_action",
    "didnt_understand": "no_action",
    "am_i_ill": "ill_questionnaire_form",
    "why_avoid_pharma": "no_action",
    "what_to_do_if_positive": "what_to_do_if_positive",
    "symptoms": "symptoms",
    "whats_your_name": "no_action",
    "ways_of_protection": "ways_of_protection",
    "underlying_conditions": "underlying_conditions",
    "personal_ways_of_protection": "ways_of_protection",
    "collective_ways_of_protection": "ways_of_protection",
    "all_ways_of_protection": "ways_of_protection",
    "test_cost": "test_cost",
    "pcr_test_cost": "test_cost",
    "rapid_test_cost": "test_cost",
    "all_test_cost": "test_cost",
    "self_test": "no_action",
    "test_types": "test_types",
    "general_knowledge_tests": "no_action",
    "out_of_scope": "no_action",
    "vaccine_stats": "vaccine_stats_form",
    "find_new_icus": "icu_stats_form",
    "positive_feedback": "no_action",
    "greetings+covid_stats": "covid_statistics_form",
    "greetings+pharma_search": "pharmacy_form",
    "greetings+ask_chitchat": "no_action",
    "thank_you+covid_stats": "covid_statistics_form",
    "greetings+whats_your_name": "no_action",
    "what_is_ilsp+what_is_athena": "no_action",
    "why_theano": "no_action",
    "may_i_ask": "no_action",
    "sorry": "no_action",
    "what_is_athena": "no_action",
    "what_is_ilsp": "no_action",
    "no_action": "no_action",
}


limited_intent_to_dialogue_dict = {
    "covid_stats": "Θα ήθελα να μάθω για τα κρούσματα στην Κίνα σήμερα",
    "EODY_faq": "Τι ξέρεις για τον ΕΟΔΥ;",
    "ask_chitchat": "Τι κάνεις;",
    "mask_faq": "Πώς φοράμε την μάσκα;",
    "vaccines": "Ποιά είναι η ανοσία που μου προσφέρει ένα εμβόλιο;",
    "pharma_search": "Υπάρχει φαρμακείο κοντά μου;",
    "greetings": "Χαίρεται!",  # maybe tell we haven't greeted ourselves
    "goodbye": "Αντίο!",
    "thank_you": "Ευχαριστώ",
    "didnt_understand": "Δεν κατάλαβα",
    "am_i_ill": "Μήπως έχω COVID-19;",
    "why_avoid_pharma": "Γιατί να αποφύγω τα φαρμακεία αν έχω COVID;",
    "what_to_do_if_positive": "Τι να κάνω αν είμαι θετικός;",
    "symptoms": "Ποιά είναι τα συμπτώματα του COVID-19",
    "whats_your_name": "Πώς σε λένε;",
    "ways_of_protection": "Πώς μπορώ να προστατευτώ από τον COVID-19;",
    "underlying_conditions": "Ποιά είναι τα υποκείμενα νοσήματα;",
    "personal_ways_of_protection": "Πώς μπορώ να προστατευτώ από τον COVID-19;",
    "collective_ways_of_protection": "Πώς μπορούμε να μειώσουμε την εξάπλωση του COVID-19;",
    "all_ways_of_protection": "Πώς μπορούμε να προστατευτούμε από τον COVID-19;",
    "test_cost": "Πόσο κοστίζει ένα τέστ;",
    "pcr_test_cost": "Πόσο κοστίζει ένα PCR τεστ;",
    "rapid_test_cost": "Πόσο κοστίζει ένα rapid τεστ;",
    "all_test_cost": "Πόσο κοστίζουν τα τεστ για τον COVID-19;",
    "self_test": "Πώς κάνω self test;",
    "test_types": "Ποιά είναι τα είδη των τέστ για COVID-19;",
    "general_knowledge_tests": "Τι ξέρεις για τα τεστ του COVID-19;",
    "out_of_scope": "Ποιό είναι το ποσοστό θνησιμότητας;",
    "vaccine_stats": "Πόσοι εμβολιασμοί έγιναν χθές;",
    "find_new_icus": "Πόσοι βρίσκονται σε ΜΕΘ σήμερα;",
    "positive_feedback": "Είσαι πολύ καλή!",
    "greetings+covid_stats": "Γεία! Πόσος κόσμος είναι θετικός σήμερα στην Ελλάδα;",
    "greetings+pharma_search": "Γεία! Μπορείς να μου βρείς ένα κοντινό φαρμακείο;",
    "greetings+ask_chitchat": "Γεία! Πώς είσαι;",
    "thank_you+covid_stats": "Ευχαριστώ! Μπορείς να μου πείς πόσα ήταν τα κρούσματα σήμερα;",
    "greetings+whats_your_name": "Γεία! Πώς σε λένε;",
    "what_is_ilsp+what_is_athena": "Τί είναι το Αθηνά και το ILSP;",
    "why_theano": "Γιατί σε λένε Θεανώ;",
    "may_i_ask": "Να ρωτήσω κάτι;",
    "sorry": "Συγγνώμη",
    "what_is_athena": "Τι είναι το Αθηνά;",
    "what_is_ilsp": "Τι είναι το ILSP;",
    "no_action": "no_action",
}

limited_intent_to_response_dict = {
    "covid_stats": "Σήμερα συνολικά υπήρξαν 0 νέα κρούσματα με συνολικό αριθμό κρουσμάτων 503302.",
    "EODY_faq": "Για πληροφορίες σχετικά με τον κορωνοϊό μπορείς να καλέσεις στο τηλέφωνο του ΕΟΔΥ 1135 όλο το εικοσιτετράωρο.",
    "ask_chitchat": "Είμαι καλά!",
    "mask_faq": "Καθάρισε τα χέρια σου με σαπούνι ή με αλκοολούχο αντισηπτικό αμέσως πριν φορέσεις τη μάσκα και οπωσδήποτε πριν την αφαιρέσεις. Τοποθέτησε τη μάσκα ώστε να καλύπτει πλήρως τη μύτη, το στόμα και το πηγούνι και να μην υπάρχουν κενά μεταξύ μάσκας και προσώπου. Πρέπει να προσέχεις να μην αγγίζεις το μπροστινό μέρος της μάσκας, καθώς θεωρείται μολυσμένο!​",
    "vaccines": "Σύμφωνα με τα έως τώρα δεδομένα, η ανοσία που σου προσφέρει το εμβόλιο κατά του κορωνοϊού υπολογίζεται να έχει διάρκεια από 6 έως 8 μήνες.",
    "pharma_search": "Πού βρίσκεσαι;",
    "greetings": "Γεία σου!",  # maybe tell we haven't greeted ourselves
    "goodbye": "Χάρηκα που τα είπαμε!",
    "thank_you": "Παρακαλώ",
    "didnt_understand": "Πώς μπορώ να σε βοηθήσω;",
    "am_i_ill": "Έχεις βήχα; (Ο διάλογος συνεχίζεται με έλεγχο συμπτωμάτων)",
    "why_avoid_pharma": "Γιατί μπορεί να κολλήσεις παραπάνω κόσμο",
    "what_to_do_if_positive": "Από τη στιγμή που είσαι φορέας, είναι σημαντικό να κρατήσεις την ψυχραιμία σου και να απομονωθείς, καθώς και να είσαι σε διαρκή επικοινωνία με το γιατρό σου ή και τον ΕΟΔΥ, ώστε σε περίπτωση που τα συμπτώματα χειροτερέψουν να ξέρεις τι να κάνεις. Άλλωστε, μην ξεχνάς οτι εγώ δεν είμαι γιατρός, οπότε δεν μπορώ να σου δώσω εξατομικευμένες ιατρικές συμβουλές.​",
    "symptoms": "Τα κύρια συμπτώματα της νόσου είναι πυρετός, βήχας και κόπωση.",
    "whats_your_name": "Με λένε Θεανώ",
    "ways_of_protection": "Ποια μέτρα προστασίας σε ενδιαφέρουν, τα ατομικά ή τα συλλογικά (δηλαδή αυτά που λαμβάνουν οι κυβερνήσεις);",
    "underlying_conditions": "Ως υποκείμενο νόσημα ορίζεται μια μακροχρόνια νόσος, η οποία απαιτεί συνήθως φαρμακευτική αγωγή και εξασθενεί το ανοσοποιητικό. ",
    "personal_ways_of_protection": "Τα κύρια μέτρα πρόληψης είναι η χρήση μάσκας, η διατήρηση αποστάσεων και το πλύσιμο των χεριών.​",
    "collective_ways_of_protection": "Τα μέτρα πρόληψης που λαμβάνουν οι κυβερνήσεις ανά τον κόσμο περιλαμβάνουν ενδεικτικά την απαγόρευση κυκλοφορίας, την υποχρεωτική χρήση μάσκας σε εσωτερικούς και εξωτερικούς χώρους, το κλείσιμο των μη-αναγκαίων καταστημάτων, καθώς και την υποχρεωτική τηλεργασία για ποσοστό εργαζομένων.​",
    "all_ways_of_protection": "Τα ατομικά μέτρα πρόληψης είναι η χρήση μάσκας, η διατήρηση αποστάσεων και το πλύσιμο των χεριών. Τα μέτρα πρόληψης που λαμβάνουν οι κυβερνήσεις ανά τον κόσμο περιλαμβάνουν ενδεικτικά την απαγόρευση κυκλοφορίας, την υποχρεωτική χρήση μάσκας σε εσωτερικούς και εξωτερικούς χώρους, το κλείσιμο των μη-αναγκαίων καταστημάτων, καθώς και την υποχρεωτική τηλεργασία για ποσοστό εργαζομένων.​",
    "test_cost": "Για ποιο τεστ θέλεις να μάθεις το κόστος;",
    "pcr_test_cost": "Βάσει Υπουργικής Απόφασης το κόστος ιδιωτικού μοριακού τεστ δεν μπορεί να ξεπερνά τα 60 ευρώ. Δημόσια όλα τα τεστ γίνονται δωρεάν.",
    "rapid_test_cost": "Βάσει Υπουργικής Απόφασης το κόστος ιδιωτικού τεστ ταχείας ανίχνευσης δεν μπορεί να ξεπερνά τα 40 ευρώ. Δημόσια όλα τα τεστ γίνονται δωρεάν.",
    "all_test_cost": "Βάσει Υπουργικής Απόφασης το κόστος για το ιδιωτικό τεστ ταχείας ανίχνευσης δεν μπορεί να ξεπερνά τα 40 ευρώ, ενω για το μοριακό τεστ δεν μπορεί να ξεπερνά τα 60 ευρώ. Τα self test έχουν διατεθεί δωρεάν από το δημόσιο για όλους, με τον περιορισμό των τεσσάρων τεστ ανά μήνα.",
    "self_test": "Το αντιγονικό τεστ αυτοεξέτασης οικιακής χρήσης (self test) μπορείς να το προμηθευτείς από το φαρμακείο της γειτονιάς σου δωρεάν με την επίδειξη του ΑΜΚΑ. Η διαδικασία είναι απλή και στη συσκευασία υπάρχουν αναλυτικές οδηγίες. Για συγκεκριμένους υπαλλήλους, όπως οι εργαζόμενοι στο λιανεμπόριο και στις εκπαιδευτικές μονάδες, το εβδομαδιαίο self test θα είναι υποχρεωτικό. Όλοι δικαιούνται ένα δωρεάν self test την εβδομάδα.",
    "test_types": "Υπάρχει το μοριακό τεστ (PCR), το οποίο θεωρείται πιο αξιόπιστο, το τεστ ταχείας ανίχνευσης αντιγόνου (rapid), το οποίο έχει το πλεονέκτημα του πολύ γρήγορου αποτελέσματος και του χαμηλού κόστους, αλλά στερείται σε αξιοπιστία. Επιπλέον, υπάρχει το αντιγονικό τεστ αυτοεξέτασης οικιακής χρήσης (self test), που μπορείς να το κάνεις μόνος σου και έχει παρόμοια χαρακτηριστικά με το rapid test.",
    "general_knowledge_tests": "Μπορώ να σε ενημερώσω σχετικά με τα είδη των τεστ, το κόστος τους, καθώς και που μπορείς να κάνεις.",
    "out_of_scope": "Μέχρι στιγμή σε παγκόσμιο επίπεδο περίπου το 3% των κρουσμάτων έχει πεθάνει από κορωνοϊό. Υπάρχουν πολλοί παράγοντες βέβαια που το επηρεάζουν, οπότε δεν μπορώ να σου απαντήσω με σιγουριά.",
    "vaccine_stats": "Χθές έγιναν ... εμβολιασμοί",
    "find_new_icus": "Σήμερα βρίσκονται ... άτομα στην ΜΕΘ",
    "positive_feedback": "Ευχαριστώ!",
    "greetings+covid_stats": "Σήμερα υπήρξαν ... κρούσματα.",
    "greetings+pharma_search": "Που βρίσκεσαι;",
    "greetings+ask_chitchat": "Είμαι μια χαρά. ",
    "thank_you+covid_stats": "Σήμερα υπήρξαν ... κρούσματα.",
    "greetings+whats_your_name": "Με λένε Θεανώ",
    "what_is_ilsp+what_is_athena": "Το Ερευνητικό Κέντρο Καινοτομίας στις Τεχνολογίες της Πληροφορίας, των Επικοινωνιών και της Γνώσης «Αθηνά» λειτουργεί από το 2003 και περιλαμβάνει τα ινστιτούτα ΙΕΛ, ΙΠΕΤ και ΙΝΒΙΣ με εγκαταστάσεις στην Αθήνα, την Ξάνθη και την Πάτρα. Στόχος του είναι η έρευνα και η καινοτομία στις Τεχνολογίες της Πληροφορικής με επιμέρους άξονες τις Τεχνολογίες Γλώσσας, Πολιτιστικής Κληρονομιάς, Δεδομένων, Βιομηχανίας και Αειφορίας, Ρομποτικής Αντίληψης και Αλληλεπίδρασης, κ.ά.",
    "why_theano": "Πήρα το όνομά μου από τη Θεανώ τη Θουρία, η οποία ήταν μια από τις διασημότερες γυναίκες επιστήμονες στην αρχαιότητα. Οι δημιουργοί μου ήθελαν να τιμήσουν τόσο τη συγκεκριμένη όσο και όλες τις γυναίκες επιστήμονες που πολλές φορές μένουν στο παρασκήνιο.",
    "may_i_ask": "Μπορείς να με ρωτήσεις ότι θέλεις!",
    "sorry": "Δεν υπάρχει κανένα πρόβλημα.",
    "what_is_athena": "Το Ερευνητικό Κέντρο Καινοτομίας στις Τεχνολογίες της Πληροφορίας, των Επικοινωνιών και της Γνώσης «Αθηνά» λειτουργεί από το 2003 και περιλαμβάνει τα ινστιτούτα ΙΕΛ, ΙΠΕΤ και ΙΝΒΙΣ με εγκαταστάσεις στην Αθήνα, την Ξάνθη και την Πάτρα. Στόχος του είναι η έρευνα και η καινοτομία στις Τεχνολογίες της Πληροφορικής με επιμέρους άξονες τις Τεχνολογίες Γλώσσας, Πολιτιστικής Κληρονομιάς, Δεδομένων, Βιομηχανίας και Αειφορίας, Ρομποτικής Αντίληψης και Αλληλεπίδρασης, κ.ά.",
    "what_is_ilsp": "Το Ινστιτούτο Επεξεργασίας του Λόγου (ΙΕΛ/ Institute for Language and Speech Processing - ILSP) λειτουργεί από το 1991 ως ένα από τα ανεξάρτητα Ινστιτούτα του Ερευνητικού Κέντρου «Αθηνά» με εγκαταστάσεις στην Αθήνα και την Ξάνθη. Στόχος του αποτελεί η βασική και εφαρμοσμένη έρευνα σε τομείς όπως η Επεξεργασία Φυσικής Γλώσσας, η Επεξεργασία, σύνθεση και αναγνώριση φωνής, η Επεξεργασία μουσικής και ήχου και η εξ αποστάσεως μάθηση.",
    "no_action": "no_action",
}


list_of_functionalities = [
    "icu_stats_form",
    "vaccine_stats_form",
    "covid_statistics_form",
    "pharmacy_form",
    "ill_questionnaire_form",
    "ways_of_protection",
    "symptoms",
    "test_types",
    "test_cost",
    "what_to_do_if_positive",
    "underlying_conditions",
    "no_action",
]


functionality_proposal = {
    "covid_statistics_form": "Θα ήθελες να μάθεις για τα κρούσματα; Έχω πληροφορίες για την Ελλάδα και τον υπόλοιπο κόσμο.",
    "pharmacy_form": "Γνωρίζω και πληροφορίες για φαρμακεία! Μήπως θέλεις να σου βρω κάποιο;",
    "ill_questionnaire_form": "Μήπως θα ήθελες να σου κάνω κάποιες ερωτήσεις εν είδει διαγνωστικού τεστ; Μην ξεχνάς ότι δεν είμαι γιατρός όμως!",
    "ways_of_protection": "Θέλεις να σε ενημερώσω σχετικά με τα μέτρα πρόληψης;",
    "test_cost": "Θα ήθελες να μάθεις πόσο κοστίζουν τα τεστ για τον κορωνοϊό;",
    "test_types": "Θα ήθελες να μάθεις ποια είναι τα διαφορετικά είδη των τεστ;",
    "what_to_do_if_positive": "Θέλεις να σου πω τι πρέπει να κάνεις σε περίπτωση που είσαι φορέας;",
    "underlying_conditions": "Γνωρίζω και σχετικά με τα υποκείμενα νοσήματα, αν σε ενδιαφέρει να μάθεις.",
    "symptoms": "Να σου πω ποια είναι τα κύρια συμπτώματα του κορωνοϊού;",
    "vaccine_stats_form": "Θέλεις να μάθεις για την εξέλιξη των εμβολιασμών στην Ελλάδα;",
    "icu_stats_form": "Ξέρω και για τις ΜΕΘ. Θέλεις να μάθεις για τη διαθεσιμότητα που υπάρχει;",
    "no_action": "Τα έχουμε πει όλα.",  # Or sth similar
}
