services:
  fastapi:
    image: side-by-side-comparison
    build: .
    ports:
      - 8104:80
    environment:
      - UID=${USID}
      - GID=${GID}
      - DB_URL=sqlite:///./production.db
      - MOCK_DIALOGUES_URL=http://mock-dialogues-service
      - SMART_SUGGEST_MICROSERVICE_URL=http://smart-suggest-microservice
    container_name: side-by-side-comparison
    hostname: side-by-side-comparison
    volumes:
      - ./production.db:/code/app/production.db
    restart: always

networks:
  default:
    name: docker_server
    external: true
