services:
  fastapi:
    image: mock-dialogues-service
    build: .
    environment:
      - UID=${USID}
      - GID=${GID}
      - DB_URL=sqlite:///./production.db
    container_name: mock-dialogues-service
    volumes:
      - ./rl_hf.dat:/code/app/rl_hf.dat
      - ./production.db:/code/app/production.db
    restart: always

networks:
  default:
    name: docker_server
    external: true
